AWSTemplateFormatVersion: 2010-09-09
Description: ALB for listening https requests and forwarding to EC2

Parameters:
  VPCStack:
    Type: String
    Default: gitlab-vpc
  SGStack:
    Type: String
    Default: gitlab-sg
  EC2Stack:
    Type: String
    Default: gitlab-ec2
  CertificateArn:
    Type: String 
    Default: arn:aws:acm:ap-northeast-1:555257342963:certificate/df515c6b-f9a1-449a-af06-86b7b246b1fc
    NoEcho: true

Resources:
  FrontLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref AWS::StackName
      Subnets:
        - Fn::ImportValue: !Sub ${VPCStack}-PublicSubnet1
        - Fn::ImportValue: !Sub ${VPCStack}-PublicSubnet2
      SecurityGroups: 
        - Fn::ImportValue: !Sub ${SGStack}-SecurityGroupLB

  FrontLBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref FrontLB
      Port: 80
      Protocol: HTTP 
      DefaultActions: 
        - Type: forward
          TargetGroupArn: !Ref FrontLBTargetGroup
#        - Type: redirect
#          RedirectConfig:
#            Protocol: HTTPS
#            Port: 443
#            Host: '#{host}'
#            Path: '/#{path}'
#            Query: '#{query}'
#            StatusCode: HTTP_301
    
  FrontLBListenerHttps:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref FrontLB
      Port: 443
      Protocol: HTTPS
      Certificates:
        - !Ref CertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref FrontLBTargetGroup

  FrontLBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${AWS::StackName}-tg
      VpcId:
        Fn::ImportValue: !Sub ${VPCStack}-VPCID
      Port: 80
      Protocol: HTTP
      HealthCheckPath: /.check_alive
      Targets:
        - Id:
            Fn::ImportValue: !Sub ${EC2Stack}-EC2Server01       

Outputs:
  FrontLBEndpoint:
    Value: !GetAtt FrontLB.DNSName
    Export:
      Name: !Sub ${AWS::StackName}-Endpoint

